#ifndef REP_PREPROCESSORTEST_MERGED_H
#define REP_PREPROCESSORTEST_MERGED_H

// This is an autogenerated file.
// Do not edit this file, any changes made will be lost the next time it is generated.

#include <QtCore/qobject.h>
#include <QtCore/qdatastream.h>
#include <QtCore/qvariant.h>
#include <QtCore/qmetatype.h>

#include <QtRemoteObjects/qremoteobjectnode.h>
#include <QtRemoteObjects/qremoteobjectpendingcall.h>
#include <QtRemoteObjects/qremoteobjectreplica.h>
#include <QtRemoteObjects/qremoteobjectsource.h>

#include <QString>

#define PREPROCESSORTEST_MACRO 1

QT_BEGIN_NAMESPACE
QT_END_NAMESPACE


#endif // REP_PREPROCESSORTEST_MERGED_H
